# Generated by Django 5.1.1 on 2024-10-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Articulos",
            new_name="Articulo",
        ),
        migrations.RenameModel(
            old_name="Clientes",
            new_name="Cliente",
        ),
        migrations.RenameModel(
            old_name="Pedidos",
            new_name="Pedido",
        ),
    ]
