# Generated by Django 5.1.1 on 2024-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_pedidos",
            "0002_rename_articulos_articulo_rename_clientes_cliente_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
