# Generated by Django 5.1.1 on 2024-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_pedidos", "0003_alter_cliente_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=10, verbose_name="Teléfono"),
        ),
    ]
